Added Splash Screen
anthaathi/anthaathi pull request #15
Opened 2022-08-26 12:50 UTC by Anm0l-K-v01d

![simulator_screenshot_8D502CE4-80BC-44D9-B6FC-79A9EF78D0B1](https://user-images.githubusercontent.com/109336573/186907155-d6fbd85a-429a-4c4b-8ead-d6a05bcdf180.png)

2022-08-28 03:35 UTC, Anm0l-K-v01d commented
![simulator_screenshot_6CB2A2A1-C7C0-4863-A29B-E00FE30FEBFD](https://user-images.githubusercontent.com/109336573/187056203-4fea746b-0966-432c-83e2-53ceb891c7e0.png)
![simulator_screenshot_D9AEB659-13C8-4942-877F-EA5BD7EC0ED7](https://user-images.githubusercontent.com/109336573/187056209-499a82b1-20a1-4591-8ee5-82d5392c7607.png)

Added new FAB, Integrated Chatwoot

2022-08-28 05:47 UTC, kedar09 commented
@Anm0l-K-v01d, please resolve merge conflicts.

2022-08-29 07:40 UTC, kedar09 approved these changes

2022-08-29 08:07 UTC, kedar09 commented on apps/anthaathi-commerce-mobile-client/src/App.tsx
> +                    key: "13"
remove this

2022-08-29 08:15 UTC, kedar09 requested changes

2022-08-29 08:15 UTC, kedar09 commented on apps/anthaathi-commerce-mobile-client/src/App.tsx
> +            </ScrollView>
remove this lines

2022-08-29 09:08 UTC, kedar09 approved these changes

2022-08-29 10:04 UTC, merged